#index:
#    path: /
#    controller: App\Controller\DefaultController::index

sum:
    path: /sum/{value1}/{value2}
    requirements:
        value1: '\d+'
        value2: '\d+'
    controller: App\Controller\SumController::sum

homepage:
    path: /
    controller: App\Controller\HomepageController::home

post_new:
    path: /posts/new
    controller: App\Controller\PostController::new
    methods: [GET, POST]
